version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    cooldown:
      default-days: 5
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"
